"""Add a admin_group_message_id field to Message Model

Revision ID: 1618a4126a75
Revises: fb1c8b34b91b
Create Date: 2026-02-12 22:20:31.291841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1618a4126a75'
down_revision: Union[str, Sequence[str], None] = 'fb1c8b34b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('admin_group_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'admin_group_message_id')
    # ### end Alembic commands ###
