"""Removed the category_id field

Revision ID: 50fff4e2380b
Revises: 2a0e51ca3a6d
Create Date: 2026-01-23 00:12:44.129198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fff4e2380b'
down_revision: Union[str, Sequence[str], None] = '2a0e51ca3a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_category_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_category_id_fkey'), 'users', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
