"""Added group_message_id row to Message table

Revision ID: 5e1e6467c6b8
Revises: 1618a4126a75
Create Date: 2026-02-22 00:58:01.538126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1e6467c6b8'
down_revision: Union[str, Sequence[str], None] = '1618a4126a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('group_message_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['group_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'group_message_id')
    # ### end Alembic commands ###
