"""Removed user field and added telegram_id field in Announcement model

Revision ID: 74cfa3efafbb
Revises: 04f69fb7c579
Create Date: 2026-04-09 21:15:29.402148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cfa3efafbb'
down_revision: Union[str, Sequence[str], None] = '04f69fb7c579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('announcements_user_id_fkey'), 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('announcements_user_id_fkey'), 'announcements', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('announcements', 'telegram_id')
    # ### end Alembic commands ###
