"""Deleted group_message_id row to Message table. Added unique=True to admin_group_message_id. Delete updated_at in Base model

Revision ID: b63b4848ccad
Revises: 5e1e6467c6b8
Create Date: 2026-02-22 01:02:31.405641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b63b4848ccad'
down_revision: Union[str, Sequence[str], None] = '5e1e6467c6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_at')
    op.drop_constraint(op.f('messages_group_message_id_key'), 'messages', type_='unique')
    op.create_unique_constraint(None, 'messages', ['admin_group_message_id'])
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'group_message_id')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('group_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='unique')
    op.create_unique_constraint(op.f('messages_group_message_id_key'), 'messages', ['group_message_id'], postgresql_nulls_not_distinct=False)
    op.add_column('categories', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
