"""Removed is_anonymous field from Message model

Revision ID: bd7208891fdb
Revises: ffd90a5aec6f
Create Date: 2026-04-08 23:10:50.042755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7208891fdb'
down_revision: Union[str, Sequence[str], None] = 'ffd90a5aec6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_anonymous')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
